### ISSUE TITLE
Format script is very unhelpful and not the same as lint

### ISSUE THREAD

**Issue by lukasoppermann** [primer/primitives#376]
## Problem
While `yarn lint` passes, `yarn format` fails. This is often only noticed in the PR as I don't run `format` and `lint`.
However the output is very unhelpful.

## Expected behavior
1. If `yarn lint` passes, `yarn format` should pass as well
2. If either fails in a PR, the issues should be reported in the action or in the PR as a comment. If people add a PR via github they have no chance of knowing what is wrong.

**Comment by rezrah** [comment]
> However the output is very unhelpful. 

@lukasoppermann - can you please post an example of the output you found unhelpful? 

> If yarn lint passes, yarn format should pass as well

🤔 Is this expected behaviour? IMO they've usually always had different responsibilities, but we can merge the commands if you and others find that more useful.

> If either fails in a PR, the issues should be reported in the action or in the PR as a comment. 

AFAIK, we don't do this anywhere, but I kinda like it as it avoids you digging into the CI workflow to see what failed.

Another option to shift-left on this would be to introduce a pre-commit hook, that brings the error to your attention sooner.

**Comment by lukasoppermann** [comment]
Hey, so first this is the output

> $ prettier --check '**/*.{js,jsx,ts,tsx,md,mdx,css}'
> Checking formatting...
> [warn] .github/pull_request_template.md
> [warn] Code style issues found in the above file. Forgot to run Prettier?
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

But I would love to know what issues were found.

**Comment by lukasoppermann** [comment]
Hey @rezrah maybe we could add the correct vs code settings for autoformat to `.vscode/settings.json`?

Would that be this?

```json
{
  "typescript.tsdk": "node_modules/typescript/lib",
  "editor.defaultFormatter": "rvest.vs-code-prettier-eslint"
}
```
