### ISSUE TITLE
Colors not accessible to people with color blindness

### ISSUE THREAD

**Issue by martinfrancois** [primer/primitives#656]
I just read the [blog post on the improved accessibility in terms of contrast](https://github.blog/2023-05-11-unlocking-inclusive-design-how-primers-color-system-is-making-github-com-more-inclusive/), which I applaud. Unfortunately however, the chosen colors, especially for "Severe" and "Danger" states, are almost indistinguishable to people with some form of color blindness, which make up around 8.5% of the population:

![Screenshot_20230517_215203_CVSimulator](https://github.com/primer/primitives/assets/14319020/9cd40cfb-92ed-48f5-871f-6f409641f333)

Being able to differentiate the two states could be quite important, which is why I think they should be changed to be more accessible.

**Comment by lukasoppermann** [comment]
Hey @martinfrancois, thank you for getting back to us on this. We do have a special mode for tritanopia and for Deutranopia + Protanopia. However the difference of the `severe` and `danger` states are not so easy to distinguish there as well.

I would argue that this is not such a problem due to two things:
1. We often use icons (not in the example screenshot above, but in real cases) to distinguish the states.
2. Both `severe` and `danger` present information that the user needs to pay close attention to. They are very similar in intend. Using a danger alert for a serve warning would not be a problem in 99% of the cases (if not 100%). This is why I think it is far more important to distinguish these two from the `Done` and `Success` as well as the `Info` state. 

If you disagree, please provide some more reasoning so that I may understand why you feel differently about this. 

Thanks.
