### ISSUE TITLE
Low contrast for ANSI colors

### ISSUE THREAD

**Issue by dominicegginton** [primer/primitives#72]
*Not sure if this is a primitives issue but am opening just in case*

[GItHub's VSCode theme](https://github.com/primer/github-vscode-theme) uses primers primitives ANSI color values for the integrated terminal color theme. There are several open issues in regards to low contrast (mostly pointing to the GitHub Light Default theme) rendering some text unreadable. Is this something the primer team can look into?

Please see https://github.com/primer/github-vscode-theme/issues/157 & https://github.com/primer/github-vscode-theme/issues/155

#### Screenshots

| GitHub Light Default | GitHub Dark Default | GitHub Dark Dimmed |
| --------------------------- | --------------------------- | ---------------------------- |
| ![screenshot-Sat-17Apr21_00 17](https://user-images.githubusercontent.com/28626241/115093459-4e7d6300-9f12-11eb-84df-00358e082ed8.png) | ![screenshot-Sat-17Apr21_00 18](https://user-images.githubusercontent.com/28626241/115093502-779df380-9f12-11eb-9101-a93776904f18.png) | ![screenshot-Sat-17Apr21_00 18_000](https://user-images.githubusercontent.com/28626241/115093518-7ff62e80-9f12-11eb-97f8-b684b8d04100.png) |

**Comment by simurai** [comment]
Was wondering about the low contrast in VS Code's terminal too and I think the problem is that on github.com the Checks (that use the ANSI colors) have a "custom" dark background in light mode:

![Screen Shot 2021-04-19 at 10 29 15](https://user-images.githubusercontent.com/378023/115169927-54359d00-a0fa-11eb-90e0-4540446e3726.png)

So the [ANSI colors](https://github.com/primer/primitives/blob/b472c14a21c0984759ec1eb97c31b096e2f069f4/data/colors/mixins/light_mode.scss#L972-L992) in light mode are kinda meant for a dark mode which doesn't really work outside of github.com. 🤔 

Hmmm.. maybe we can look into a way where we can have a "permanent theme" (dark checks in light mode)? I guess as a short term fix we could add custom `checks-ansi` colors that work for dotcom and change the existing `ansi` colors to work on a light background.
