### ISSUE TITLE
Map v1 variables to v2 variables

### ISSUE THREAD

**Issue by colebemis** [primer/primitives#95]
## Context

We will know that the [v2 color system](https://github.com/github/design-systems/issues/1388) has full coverage of the existing color system when every variable currently in Primer Primitives (v1) can be either mapped to a v2 variable or moved into github/github as an app-level variable.

## Do this

In the [`colors_v2`](https://github.com/primer/primitives/tree/main/data/colors_v2) directory of [primer/primitives](https://github.com/primer/primitives), add mappings for all v1 variables. Every v1 variable should be mapped to one of the following:
  - a v2 global variable (e.g. `var(--color-fg-default)`)
  - a v2 component variable (e.g. `var(--color-btn-primary-bg)`)
  - a scale variable (Only variables intended to be moved out of primer/primitives and into github/github can use scale variables. Indicate that a variable should be moved to github/github with a code comment)

  Use the [Migration spreadsheet](https://docs.google.com/spreadsheets/d/1vL-FPM7-NvTsHgKBRur543jnuzQJqJ69Fl6pH8EyKy4/edit#gid=752100387) as a reference.

## Example

Here's an example diff showing how to add a mapping from `text-primary` (v1 variable) to `fg-default` (v2 variable):

```diff
diff --git a/data/colors_v2/mixins/migration.scss b/data/colors_v2/mixins/migration.scss
index 9892178..a723b4a 100644
--- a/data/colors_v2/mixins/migration.scss
+++ b/data/colors_v2/mixins/migration.scss
@@ -2,3 +2,6 @@
 
 // Mapping of v1 variables to v2 variables
 
+$text: (
+  primary: var(--color-fg-default),
+);
diff --git a/data/colors_v2/mixins/dark_mode.scss b/data/colors_v2/mixins/dark_mode.scss
index f64f1b4..e55756c 100644
--- a/data/colors_v2/mixins/dark_mode.scss
+++ b/data/colors_v2/mixins/dark_mode.scss
@@ -87,4 +87,5 @@ $export: (
   ),
 
   // Mapping of v1 variables to v2 variables
+  text: $text,
 );
diff --git a/data/colors_v2/mixins/light_mode.scss b/data/colors_v2/mixins/light_mode.scss
index a5d9087..a2a411f 100644
--- a/data/colors_v2/mixins/light_mode.scss
+++ b/data/colors_v2/mixins/light_mode.scss
@@ -87,4 +87,5 @@ $export: (
   ),
   
   // Mapping of v1 variables to v2 variables
+  text: $text,
 );
```

## Acceptance criteria

This issue is complete when the `v2 coverage` check in primer/primitives outputs `100%`:

![CleanShot 2021-05-14 at 11 31 31@2x](https://user-images.githubusercontent.com/4608155/118313773-18e37f80-b4a8-11eb-8bb1-80536f87c2af.png)

**Comment by simurai** [comment]
**Update**: Conversion of https://github.com/primer/primitives/pull/94 went up to around `77%` but now it's down to `64.78%` again. Here some things that need to be solved or decided so we can get closer to `100%`:

- [ ] What should the mapping be for v1 variables that we don't have a replacement, but also we don't want to keep in v2. E.g. all the `auto`, `shadow`, `fade` variables.
  - [ ] Maybe we add a `--color-deprecated: red` and use that so it's easy to see if something needs replacement.
- [ ] We plan to move all app variables to dotcom, but some of them use `rgba()` and other color functions. There is currently no support on dotcom. So we'd 
  - [ ] Add SASS support on dotcom
  - [ ] Only move scale variables, but keep color functions in Primitives
  - [ ] For `rgba()` we might can output the scales into `HSL` format which supports transparency with CSS variables. `hsla(var(--hsl-gray-5), 10%)`
- [ ] There are a lot `transparent` borders in light mode. It's because in dark mode we show a solid border with a semi transparent background.
  - [ ] Should we keep as is
  - [ ] or try to reduce these style changes between light and dark mode?
- [ ] What should we do with the marketing variables? Currently marketing (Gloss) pages don't use color modes and have a separate scale. I think we should either
  - [ ] Move them back to Primer CSS (for now).
  - [ ] Or only use `scale` colors and add support for color modes.
- [ ] Should we move the `ansi` colors to the VS Code theme. It's currently the only place that used them that I know of. Actions logs uses them too, but they have a custom version that stays dark in light mode.

**Comment by simurai** [comment]
**Update**: Conversion is now at `87.60%`.

Only thing left are the `auto` and `fade` variables. We'll have to see how easy it will be to replace them.
